### ISSUE TITLE
Adding a custom icon for an item is causing an error 

### ISSUE THREAD

**Issue by prolificcoder** [zhaocai/alfred-workflow#7]
I am trying add an item with a custom icon with (I have the icon in the workflow directory already) 
fb.add_item({
                      :subtitle => json_response['domain'],
                      :title => 'Your domain is available',
                      :valid => "yes",
                      :icon => 'avaliable.png'
                  })

But I am getting this error

E, [2015-02-21 18:08:02 #10861] ERROR -- mobiletest.engineer.godaddy-domains: A fatal error has occurred. You may seek help in the Alfred supporting site, forum or raise an issue in the bug tracking site.
  #<TypeError: no implicit conversion of Symbol into Integer>
  /Library/Ruby/Gems/2.0.0/gems/alfred-workflow-1.8.0/lib/alfred/feedback/item.rb:109:in `[]'  
/Library/Ruby/Gems/2.0.0/gems/alfred-workflow-1.8.0/lib/alfred/feedback/item.rb:109:in`to_xml'  
/Library/Ruby/Gems/2.0.0/gems/alfred-workflow-1.8.0/lib/alfred/feedback.rb:26:in `block in to_xml'  
/Library/Ruby/Gems/2.0.0/gems/alfred-workflow-1.8.0/lib/alfred/feedback.rb:25:in`each'  
/Library/Ruby/Gems/2.0.0/gems/alfred-workflow-1.8.0/lib/alfred/feedback.rb:25:in `to_xml'  
./main.rb:60:in`block in <main>'  

Is this a bug or is there someother way to add custom icon?

**Comment by zhaocai** [comment]
can you try to upgrade alfred-workflow gem?
